# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wreport_par.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Report_par1(object):
    def setupUi(self, Report_par1):
        Report_par1.setObjectName("Report_par1")
        Report_par1.setWindowModality(QtCore.Qt.WindowModal)
        Report_par1.resize(460, 200)
        Report_par1.setModal(True)
        self.label = QtWidgets.QLabel(Report_par1)
        self.label.setGeometry(QtCore.QRect(10, 20, 141, 27))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Report_par1)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 141, 33))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Report_par1)
        self.label_3.setGeometry(QtCore.QRect(10, 87, 141, 33))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Report_par1)
        self.lineEdit.setGeometry(QtCore.QRect(160, 20, 112, 27))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(Report_par1)
        self.comboBox.setGeometry(QtCore.QRect(160, 50, 261, 33))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(Report_par1)
        self.comboBox_2.setGeometry(QtCore.QRect(160, 87, 261, 33))
        self.comboBox_2.setObjectName("comboBox_2")
        self.splitter = QtWidgets.QSplitter(Report_par1)
        self.splitter.setGeometry(QtCore.QRect(160, 140, 200, 34))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pushButton = QtWidgets.QPushButton(self.splitter)
        self.pushButton.setBaseSize(QtCore.QSize(100, 0))
        self.pushButton.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/22x22/actions/document-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setDefault(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_2.setBaseSize(QtCore.QSize(100, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/22x22/actions/dialog-cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Report_par1)
        QtCore.QMetaObject.connectSlotsByName(Report_par1)
        Report_par1.setTabOrder(self.lineEdit, self.comboBox)
        Report_par1.setTabOrder(self.comboBox, self.comboBox_2)
        Report_par1.setTabOrder(self.comboBox_2, self.pushButton)
        Report_par1.setTabOrder(self.pushButton, self.pushButton_2)

    def retranslateUi(self, Report_par1):
        _translate = QtCore.QCoreApplication.translate
        Report_par1.setWindowTitle(_translate("Report_par1", "Параметри звіту"))
        self.label.setText(_translate("Report_par1", "Номер документа"))
        self.label_2.setText(_translate("Report_par1", "Документ склав"))
        self.label_3.setText(_translate("Report_par1", "Документ перевірив"))
        self.pushButton.setText(_translate("Report_par1", "Звіт"))
        self.pushButton_2.setText(_translate("Report_par1", "Відміна"))
